
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-flinkoperator-streamnative-io-v1beta1-flinkcluster
  failurePolicy: Fail
  name: mflinkcluster.flinkoperator.streamnative.io
  rules:
  - apiGroups:
    - flinkoperator.streamnative.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinkclusters
  sideEffects: NoneOnDryRun

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-flinkoperator-streamnative-io-v1beta1-flinkcluster
  failurePolicy: Fail
  name: vflinkcluster.flinkoperator.streamnative.io
  rules:
  - apiGroups:
    - flinkoperator.streamnative.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinkclusters
  sideEffects: NoneOnDryRun
